STRINGS = {
    "welcome": "مرحبًا بك في SparkTalks",
    "find_partner": "ابحث عن شريك",
    "settings": "الإعدادات",
    "vip_store": "متجر VIP",
    "profile": "الملف الشخصي",
    "next": "التالي",
    "end_chat": "إنهاء المحادثة",
    "report": "إبلاغ",
    "block": "حظر",
    "good_morning": "صباح الخير",
    "good_afternoon": "مساء الخير",
    "good_evening": "مساء الخير",
    "good_night": "تصبح على خير",
    "searching": "جاري البحث...",
    "chat_ended": "انتهت المحادثة",
    "vip_required": "VIP مطلوب",
    "banned": "أنت محظور",
    "maintenance": "تحت الصيانة",
    "contact_blocked": "مشاركة جهات الاتصال محظورة",
    "invite_earn": "دعوة واكسب",
    "language": "اللغة",
    "timezone": "المنطقة الزمنية",
    "theme": "سمة المحادثة",
    "voice_room": "غرفة صوتية",
    "my_vip": "حسابي VIP",
}