STRINGS = {
    "welcome": "Welcome to SparkTalks",
    "find_partner": "Find Partner",
    "settings": "Settings",
    "vip_store": "VIP Store",
    "profile": "Profile",
    "next": "Next",
    "end_chat": "End Chat",
    "report": "Report",
    "block": "Block",
    "good_morning": "Good Morning",
    "good_afternoon": "Good Afternoon",
    "good_evening": "Good Evening",
    "good_night": "Good Night",
    "searching": "Searching for a partner...",
    "chat_ended": "Chat ended",
    "vip_required": "VIP required",
    "banned": "You have been banned",
    "maintenance": "Under maintenance",
    "contact_blocked": "Contact sharing blocked",
    "invite_earn": "Invite & Earn",
    "language": "Language",
    "timezone": "Timezone",
    "theme": "Chat Theme",
    "voice_room": "Voice Room",
    "my_vip": "My VIP",
}