STRINGS = {
    "welcome": "SparkTalks में आपका स्वागत है",
    "find_partner": "साथी खोजें",
    "settings": "सेटिंग्स",
    "vip_store": "VIP स्टोर",
    "profile": "प्रोफाइल",
    "next": "अगला",
    "end_chat": "चैट बंद करें",
    "report": "रिपोर्ट",
    "block": "ब्लॉक",
    "good_morning": "सुप्रभात",
    "good_afternoon": "नमस्कार",
    "good_evening": "शुभ संध्या",
    "good_night": "शुभ रात्रि",
    "searching": "साथी की तलाश में...",
    "chat_ended": "चैट समाप्त",
    "vip_required": "VIP आवश्यक",
    "banned": "आप बैन हैं",
    "maintenance": "मेंटेनेंस जारी है",
    "contact_blocked": "संपर्क साझा करना ब्लॉक किया गया",
    "invite_earn": "आमंत्रित करें और कमाएं",
    "language": "भाषा",
    "timezone": "समय क्षेत्र",
    "theme": "चैट थीम",
    "voice_room": "वॉइस रूम",
    "my_vip": "मेरा VIP",
}