STRINGS = {
    "welcome": "Добро пожаловать в SparkTalks",
    "find_partner": "Найти партнёра",
    "settings": "Настройки",
    "vip_store": "VIP Магазин",
    "profile": "Профиль",
    "next": "Далее",
    "end_chat": "Завершить",
    "report": "Жалоба",
    "block": "Блокировать",
    "good_morning": "Доброе утро",
    "good_afternoon": "Добрый день",
    "good_evening": "Добрый вечер",
    "good_night": "Спокойной ночи",
    "searching": "Поиск партнёра...",
    "chat_ended": "Чат завершён",
    "vip_required": "Требуется VIP",
    "banned": "Вы заблокированы",
    "maintenance": "Тех. обслуживание",
    "contact_blocked": "Обмен контактами заблокирован",
    "invite_earn": "Пригласи и получи",
    "language": "Язык",
    "timezone": "Часовой пояс",
    "theme": "Тема чата",
    "voice_room": "Голосовая комната",
    "my_vip": "Мой VIP",
}